spring:
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
logging:
  level:
    sql: debug
